/**
 * EventDto 运行时校验（Zod，AGENTS.md §8.4 完整落地——2026-08-23 遗留#4）。
 *
 * SSE 数据必须通过本 schema 才进入业务层，防止后端 schema 漂移导致
 * 运行时 undefined。KNOWN_EVENT_KINDS 由 scripts/gen-types-post.mjs 从
 * src/api/generated/EventDto.ts 的判别联合自动提取（单一事实源，
 * 2026-08-25 审查 F-guard：手抄清单漂移曾把 reasoning_delta/session_created/
 * step_started/step_ended 静默丢弃）。
 *
 * This file is auto-generated by scripts/gen-types-post.mjs. Do not edit manually.
 */
import { z } from "zod";

const KNOWN_EVENT_KINDS = z.enum([
  "token",
  "reasoning_delta",
  "message_appended",
  "turn_streaming_started",
  "turn_end",
  "tool_call_started",
  "tool_call_finished",
  "session_created",
  "permission_requested",
  "permission_resolved",
  "permission_mode_changed",
  "task_updated",
  "config_changed",
  "step_started",
  "step_ended",
]);

export const eventDtoSchema = z
  .object({
    type: KNOWN_EVENT_KINDS,
    seq: z.number().optional(),
  })
  .passthrough();

export type ParsedEventDto = z.infer<typeof eventDtoSchema> & Record<string, unknown>;

/** 校验并返回类型化事件；失败返回 `null`（调用方 warn 后丢弃）。 */
export function isEventDto(
  value: unknown,
): value is { type: string; seq?: number } & Record<string, unknown> {
  return eventDtoSchema.safeParse(value).success;
}
